apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  ports:
    - port: 3002
  selector:
    app: demo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: demo-service:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3002"
