apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  ports:
    - port: 3002
  selector:
    app: finance-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
spec:
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
        - name: finance-service
          image: finance-service:latest
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3002"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
